variable "aws_region" {}
variable "vpc_cidr" {}
variable "vpc_name" {}
variable "subnet_name" {}
variable "igw_name" {}
variable "route_table_name" {}
variable "rt_cidr" {}
variable "ec2_az" {}
variable "ec2_type" {}
variable "key_name" {}
variable "subnet_cidr" {}
variable "security_group_name" {}